### ISSUE TITLE
Problème Cross Domain request

### ISSUE THREAD

**Issue by Adamatt** [guillaumeperes/strawpoll_backoffice#10]
L'API ne fonctionne pas sur un serveur distant étant donné que les headers concernant le contrôle d'accès cross domain (Access-Control-Allow-Origin etc) ne sont pas spécifiés dans les requêtes de retour.

**Comment by guillaumeperes** [comment]
J'ai ajouté un module Laravel au projet pour ajouter les headers http qu'il faut.

C'est corrigé dans ce commit : https://github.com/guillaumeperes/strawpoll_backoffice/commit/8ea65b556e0786a2946ad36f4ed347369b56e33c

Lien du module : https://github.com/barryvdh/laravel-cors
