### ISSUE TITLE
Retourner l'ID du sondage lors de la soumission

### ISSUE THREAD

**Issue by Adamatt** [guillaumeperes/strawpoll_backoffice#11]
Actuellement, lors de la soumission d'un sondage, l'API retourne l'URL complète du JSON correspondant à ce sondage
![image](https://cloud.githubusercontent.com/assets/9706674/25428583/883fc714-2a76-11e7-8b33-9a803da5bb29.png)

Il faudrait retourner uniquement l'identifiant du sondage

**Comment by guillaumeperes** [comment]
Je rajoute l'id
