### ISSUE TITLE
Format des dates du sondage

### ISSUE THREAD

**Issue by guillaumeperes** [guillaumeperes/strawpoll_backoffice#16]
https://api.strawpoll.guillaumeperes.fr/api/poll/64

Les dates created, updated et published qu'on obtient lorsque l'on récupère les données d'un sondage sont au format timestamp.

Il faudrait les convertir au format JJ/MM/AAAA, comme ça on pourra s'en servir dans les interfaces.

Le code qui gère ça se trouve ici : https://github.com/guillaumeperes/strawpoll_backoffice/blob/master/app/Poll.php

**Comment by seb9122** [comment]
résolue
