### ISSUE TITLE
Serveur de websocket inaccessible derrière un proxy 

### ISSUE THREAD

**Issue by seb9122** [guillaumeperes/strawpoll_backoffice#21]
Impossible d'afficher la page des résultats lorsqu'un utilisateur est connecté a un réseau possédant un proxy.

**Comment by guillaumeperes** [comment]
Le problème vient du fait que le port utilisé par le serveur de websocket (le port 5678) peut être bloqué par un proxy. 

Pour éviter ça, il faudra certainement faire passer les données à destination du serveur de websocket par le port 443 et configurer nginx pour les rediriger vers ce dernier.
