### ISSUE TITLE
Générer des couleurs pour les graphiques de résultats

### ISSUE THREAD

**Issue by Adamatt** [guillaumeperes/strawpoll_backoffice#22]
Actuellement avec ChartJS, le graphique n'a qu'une seule couleur par défaut et ce n'est pas très lisible, on a du mal à différencier les réponses.
Il faudrait générer une couleur pour chaque réponse et l'enregistrer dans la base afin de garder une même couleur pour une réponse donnée.

**Comment by guillaumeperes** [comment]
Pour cela, on va ajouter une nouvelle colonne à la table des answers et générer un code couleur en hexa pour chaque réponse qu'on va stocker dans cette nouvelle colonne.

De cette manière, chaque réponse aura sa couleur associée qui ne changera jamais.
