### ISSUE TITLE
Prise en compte du paramètre has_captcha

### ISSUE THREAD

**Issue by Adamatt** [guillaumeperes/strawpoll_backoffice#7]
Dans la requête coté client, le paramètre has_captcha est bien à "false"
![image](https://cloud.githubusercontent.com/assets/9706674/25427715/b4a3e4e6-2a73-11e7-9f04-d2a1367a2c94.png)

Pourtant le sondage est créé avec has_captcha=true
![image](https://cloud.githubusercontent.com/assets/9706674/25427765/dbfa95e4-2a73-11e7-9186-68c05947089c.png)

**Comment by guillaumeperes** [comment]
En utilisant axios, on ne semble plus avoir ce problème.
