### ISSUE TITLE
Les listes JSON sont déjà triées

### ISSUE THREAD

**Issue by Adamatt** [guillaumeperes/strawpoll_backoffice#8]
![image](https://cloud.githubusercontent.com/assets/9706674/25427892/42fce6b6-2a74-11e7-9d73-97d7a2538225.png)

Je me demande s'il faut vraiment avoir la clé "position" pour chaque réponse étant donné qu'une liste JSON est triée. Coté front, les questions sont envoyées dans l'ordre, côté serveur elle sont renvoyées dans l'ordre aussi, il faudrait donc peut être supprimer cette clé inutile?

**Comment by guillaumeperes** [comment]
On peut la retirer effectivement vu que le tableau de réponses retourné est déjà trié par position.

On ne s'en servira que du côté du serveur pour stocker l'ordre des réponses et faire le tri.
