### ISSUE TITLE
Problème mixed-content

### ISSUE THREAD

**Issue by Adamatt** [guillaumeperes/strawpoll_backoffice#9]
L'API ne peut pas être utilisée sur un autre serveur sécurisé via le protocole SSL puisque le back office ne l'est pas, et les navigateurs déclenchent une exception de mixed-content.
Il faudrait configurer un certificat sur le serveur pour qu'il passe en https aussi

**Comment by guillaumeperes** [comment]
J'ai installé un certificat SSL sur le serveur sur lequel est installé l'api. nginx est configuré pour utiliser https au lieu de http.
